name: PHP CI

on: [push]

jobs:
    build-test:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                php-version:
                    - '8.1'

                symfony-version:
                    - '6.1'

        name: PHP ${{ matrix.php-version }} and Symfony ${{ matrix.symfony-version }}
        steps:
            - uses: actions/checkout@v2

            - uses: shivammathur/setup-php@v2
              with:
                  php-version: "${{ matrix.php-version }}"
                  extensions: gd, zip

            - run: composer validate

            - id: composer-cache
              run: echo "::set-output name=dir::$(composer config cache-files-dir)"

            - uses: actions/cache@v1
              with:
                  path: ${{ steps.composer-cache.outputs.dir }}
                  key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                  restore-keys: ${{ runner.os }}-composer-

            - name: Install dependencies
              run: |
                  composer install

            - name: Setup fixture app
              run: |
                  cd fixture-app && composer install

            - name: Test
              run: |
                  vendor/bin/phpunit
