name: PHP CI

on: [push]

jobs:
    build-test:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                include:
                    - { php-version: "8.1", symfony-version: "6.0", phpunit-version: "9.6" }
                    - { php-version: "8.1", symfony-version: "6.1", phpunit-version: "9.6" }
                    - { php-version: "8.1", symfony-version: "6.2", phpunit-version: "9.6" }
                    - { php-version: "8.1", symfony-version: "6.3", phpunit-version: "9.6" }
                    - { php-version: "8.1", symfony-version: "6.4", phpunit-version: "9.6" }

                    - { php-version: "8.2", symfony-version: "6.0", phpunit-version: "9.6" }
                    - { php-version: "8.2", symfony-version: "6.1", phpunit-version: "9.6" }
                    - { php-version: "8.2", symfony-version: "6.2", phpunit-version: "9.6" }
                    - { php-version: "8.2", symfony-version: "6.3", phpunit-version: "9.6" }
                    - { php-version: "8.2", symfony-version: "6.4", phpunit-version: "9.6" }
                    - { php-version: "8.2", symfony-version: "7.0", phpunit-version: "9.6" }

                    - { php-version: "8.1", symfony-version: "6.0", phpunit-version: "10" }
                    - { php-version: "8.1", symfony-version: "6.1", phpunit-version: "10" }
                    - { php-version: "8.1", symfony-version: "6.2", phpunit-version: "10" }
                    - { php-version: "8.1", symfony-version: "6.3", phpunit-version: "10" }
                    - { php-version: "8.1", symfony-version: "6.4", phpunit-version: "10" }

                    - { php-version: "8.2", symfony-version: "6.0", phpunit-version: "10" }
                    - { php-version: "8.2", symfony-version: "6.1", phpunit-version: "10" }
                    - { php-version: "8.2", symfony-version: "6.2", phpunit-version: "10" }
                    - { php-version: "8.2", symfony-version: "6.3", phpunit-version: "10" }
                    - { php-version: "8.2", symfony-version: "6.4", phpunit-version: "10" }
                    - { php-version: "8.2", symfony-version: "7.0", phpunit-version: "10" }

        name: PHP ${{ matrix.php-version }}, Symfony ${{ matrix.symfony-version }}, PHPUnit ${{ matrix.phpunit-version }}
        steps:
            - uses: actions/checkout@v4

            - uses: shivammathur/setup-php@v2
              with:
                  php-version: "${{ matrix.php-version }}"
                  extensions: gd, zip

            - run: composer validate

            - id: composer-cache
              run: echo "::set-output name=dir::$(composer config cache-files-dir)"

            - uses: actions/cache@v3
              with:
                  path: ${{ steps.composer-cache.outputs.dir }}
                  key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
                  restore-keys: ${{ runner.os }}-composer-

            - name: Install dependencies
              run: |
                  composer update --with "symfony/framework-bundle:^${{ matrix.symfony-version }}" --with "phpunit/phpunit:^${{ matrix.phpunit-version }}"

            - name: Setup fixture app
              working-directory: ./fixture-app
              run: |
                  sed -i 's/"require": "6.1.*"/"require": "${{ matrix.symfony-version }}.*"/g' composer.json
                  composer update --with "phpunit/phpunit:^${{ matrix.phpunit-version }}"

            - name: Test
              env:
                  XDEBUG_MODE: coverage
              run: |
                  vendor/bin/phpunit --coverage-text --configuration phpunit-${{ matrix.phpunit-version }}.xml
